version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: logistics_db
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  logistics-service:
    build:
      context: .
      args:
        SERVICE_NAME: logistics_service
    command: bal run target/bin/logistics_system.jar
    environment:
      - KAFKA_HOST=kafka:9092
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - DB_NAME=logistics_db
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy

  standard-delivery-service:
    build:
      context: .
      args:
        SERVICE_NAME: standard_delivery_service
    command: bal run target/bin/logistics_system.jar
    environment:
      - KAFKA_HOST=kafka:9092
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - DB_NAME=logistics_db
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy

  express-delivery-service:
    build:
      context: .
      args:
        SERVICE_NAME: express_delivery_service
    command: bal run target/bin/logistics_system.jar
    environment:
      - KAFKA_HOST=kafka:9092
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - DB_NAME=logistics_db
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy

  international-delivery-service:
    build:
      context: .
      args:
        SERVICE_NAME: international_delivery_service
    command: bal run target/bin/logistics_system.jar
    environment:
      - KAFKA_HOST=kafka:9092
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - DB_NAME=logistics_db
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy